# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
        os: [windows-latest]
    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     - name : checkout master
       uses: actions/checkout@master
      
     - name: Set up Node.js
       uses: actions/setup-node@master
       with:
          node-version: 12.18.0
      
     - name: install node tools
       run: npm install --global --production windows-build-tools@4.0.0
     
     - name: install
       run : yarn global add neon-cli
              
     - name: Install yarn dependencies
       run: yarn install
    
     - name: Rebuild Project
       run: yarn --force
     
     - name: Run Unit test Cases for rust code
       run: cargo test --manifest-path parser/native/Cargo.toml --release  
    
      

